### PR TITLE
Improve Coordination Party 

### PR DESCRIPTION
**Pull request by developerfred**
1. In the top nav there is a duplicate icon, not sure why, one leads to pay and the other one to fund. Do I need to design a new logo/icon? ✅ 
2. I still can't see the svg animations I've sent for hover / mouse out ✅ 
3. The background for each thumbnail should stay and not disappear. If it does disappear it should be gradual from 100 to 0, not all of a sudden. ✅ 

### New Figma Version

Screenshot 2021-12-06 at 23 09 20
Screenshot 2021-12-06 at 23 09 20

### CODE REVIEW

**Comment by developerfred** [comment]
@owocki

**Comment by owocki** [comment]
> This branch has conflicts that must be resolved

@developerfred can u resolve the conflicts.

**Comment by owocki** [comment]
just merged this + it now seems like the layout is all messed up :/ https://coordination.party/

**Comment by owocki** [comment]
screencapture-coordination-party-2021-12-06-16_11_23

**Comment by developerfred** [comment]
@owocki Go back to the old version, I'll see what happened.

**Comment by developerfred** [comment]
@owocki fixed!

**Pull request merged**
